# Copyright © 2024 Cask Data, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.

@File_Sink
Feature:File Sink - Verification of Excel Plugin to File Successful data transfer

  @File_Sink_Required @EXCEL_TEST @FILE_SINK_TEST
  Scenario: To verify data is getting transferred from Excel source to File sink
    Given Open Datafusion Project to configure pipeline
    When Select plugin: "Excel" from the plugins list as: "Source"
    When Expand Plugin group in the LHS plugins list: "Sink"
    When Select plugin: "File" from the plugins list as: "Sink"
    Then Connect plugins: "Excel" and "File" to establish connection
    Then Navigate to the properties page of plugin: "Excel"
    Then Enter input plugin property: "referenceName" with value: "FileReferenceName"
    Then Enter input plugin property: "filePath" with value: "excelTestFile"
    Then Enter input plugin property: "filePattern" with value: "Pattern"
    Then Select dropdown plugin property: "sheet" with option value: "Sheet Name"
    Then Enter input plugin property: "sheetValue" with value: "Sheet1"
    Then Enter Value for plugin property table key : "columnList" with values: "columnvalues"
    Then Enter key value pairs for plugin property: "columnMapping" with values from json: "columnmappings"
    Then Validate "Excel" plugin properties
    Then Close the Plugin Properties page
    Then Navigate to the properties page of plugin: "File"
    Then Enter input plugin property: "referenceName" with value: "FileReferenceName"
    Then Enter input plugin property: "path" with value: "fileSinkTargetBucket"
    Then Replace input plugin property: "pathSuffix" with value: "yyyy-MM-dd-HH-mm"
    Then Select dropdown plugin property: "format" with option value: "csv"
    Then Validate "File" plugin properties
    Then Close the Plugin Properties page
    Then Save the pipeline
    Then Deploy the pipeline
    Then Run the Pipeline in Runtime
    Then Wait till pipeline is in running state
    Then Open and capture logs
    Then Verify the pipeline status is "Succeeded"
    Then Close the pipeline logs
    Then Validate output file generated by file sink plugin "fileSinkTargetBucket" is equal to expected output file "outputForExcelTest"
